# Generated by Django 5.2.4 on 2026-07-31 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.FloatField(verbose_name='Resistor R1 (Ohms)')),
                ('r2', models.FloatField(verbose_name='Resistor R2 (Ohms)')),
                ('rc', models.FloatField(verbose_name='Resistor RC (Ohms)')),
                ('re', models.FloatField(verbose_name='Resistor RE (Ohms)')),
                ('c1', models.FloatField(verbose_name='Capacitor C1 (uF)')),
                ('c2', models.FloatField(verbose_name='Capacitor C2 (uF)')),
                ('gain', models.FloatField(verbose_name='Voltage Gain (dB)')),
                ('cutoff_frequency', models.FloatField(verbose_name='Cutoff Frequency (Hz)')),
                ('phase_margin', models.FloatField(verbose_name='Phase Margin (Degrees)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction Record',
                'verbose_name_plural': 'Prediction History',
                'ordering': ['-created_at'],
            },
        ),
    ]
