# Generated by Django 5.2.4 on 2026-07-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surrogate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Circuit Prediction Record', 'verbose_name_plural': 'Circuit Prediction History'},
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='cutoff_frequency',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='gain',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='phase_margin',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='r1',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='r2',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='rc',
        ),
        migrations.RemoveField(
            model_name='predictionhistory',
            name='re',
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='circuit_category',
            field=models.CharField(default='Amplifiers', max_length=64),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='circuit_slug',
            field=models.CharField(default='common-emitter', max_length=64),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='circuit_title',
            field=models.CharField(default='Common Emitter Amplifier', max_length=128),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='inputs_json',
            field=models.TextField(default='{}', help_text='JSON string of input component values'),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='outputs_json',
            field=models.TextField(default='{}', help_text='JSON string of predicted outputs'),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='performance_score',
            field=models.FloatField(default=95.0, verbose_name='Performance Score (%)'),
        ),
    ]
