# Generated by Django 5.2.4 on 2026-08-08 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surrogate_app', '0002_alter_predictionhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseDesignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_slug', models.CharField(default='rc-low-pass', max_length=64)),
                ('circuit_title', models.CharField(default='RC Low Pass Filter', max_length=128)),
                ('algorithm_used', models.CharField(default='Genetic Algorithm', max_length=64)),
                ('comp_series', models.CharField(default='E24', max_length=16)),
                ('target_params_json', models.TextField(default='{}', help_text='Target output specs JSON')),
                ('optimized_components_json', models.TextField(default='{}', help_text='Recommended optimal component values JSON')),
                ('predicted_params_json', models.TextField(default='{}', help_text='ML validated predicted outputs JSON')),
                ('performance_score', models.FloatField(default=95.0, verbose_name='Optimization Score (%)')),
                ('total_error', models.FloatField(default=0.0, verbose_name='Total Error (%)')),
                ('iterations', models.IntegerField(default=60)),
                ('optimization_time_ms', models.IntegerField(default=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reverse Design Record',
                'verbose_name_plural': 'Reverse Design History',
                'ordering': ['-created_at'],
            },
        ),
    ]
