# Generated by Django 5.2.4 on 2026-08-11 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surrogate_app', '0003_reversedesignhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLearningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_slug', models.CharField(default='rc-low-pass', max_length=64)),
                ('circuit_title', models.CharField(default='RC Low Pass Filter', max_length=128)),
                ('initial_samples', models.IntegerField(default=50)),
                ('added_samples', models.IntegerField(default=50)),
                ('final_samples', models.IntegerField(default=100)),
                ('iterations', models.IntegerField(default=5)),
                ('sampling_strategy', models.CharField(default='Uncertainty Sampling', max_length=64)),
                ('initial_r2', models.FloatField(default=0.88)),
                ('final_r2', models.FloatField(default=0.982)),
                ('initial_mae', models.FloatField(default=0.85)),
                ('final_mae', models.FloatField(default=0.21)),
                ('improvement_pct', models.FloatField(default=75.3)),
                ('results_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_learning_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Active Learning Record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonteCarloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_slug', models.CharField(default='rc-low-pass', max_length=64)),
                ('circuit_title', models.CharField(default='RC Low Pass Filter', max_length=128)),
                ('tolerance_pct', models.FloatField(default=5.0)),
                ('simulations_count', models.IntegerField(default=1000)),
                ('inputs_json', models.TextField(default='{}')),
                ('results_json', models.TextField(default='{}')),
                ('robustness_score', models.FloatField(default=94.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monte_carlo_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monte Carlo Record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParetoOptimizationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_slug', models.CharField(default='common-emitter', max_length=64)),
                ('circuit_title', models.CharField(default='Common Emitter Amplifier', max_length=128)),
                ('algorithm', models.CharField(default='NSGA-II / Multi-Objective PSO', max_length=64)),
                ('objectives_json', models.TextField(default='[]')),
                ('pareto_solutions_json', models.TextField(default='[]')),
                ('designs_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pareto_optimizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pareto Optimization Record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitivityAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_slug', models.CharField(default='common-emitter', max_length=64)),
                ('circuit_title', models.CharField(default='Common Emitter Amplifier', max_length=128)),
                ('selected_component', models.CharField(default='RC', max_length=32)),
                ('variation_range_pct', models.FloatField(default=20.0)),
                ('sensitivity_scores_json', models.TextField(default='{}')),
                ('robust_design_json', models.TextField(default='{}')),
                ('robustness_score', models.FloatField(default=93.8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitivity_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sensitivity Analysis Record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UncertaintyAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_slug', models.CharField(default='common-emitter', max_length=64)),
                ('circuit_title', models.CharField(default='Common Emitter Amplifier', max_length=128)),
                ('model_type', models.CharField(default='Random Forest Ensemble', max_length=64)),
                ('inputs_json', models.TextField(default='{}')),
                ('results_json', models.TextField(default='{}')),
                ('confidence_score', models.FloatField(default=95.0)),
                ('mae', models.FloatField(default=0.15)),
                ('rmse', models.FloatField(default=0.22)),
                ('r2_score', models.FloatField(default=0.985)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uncertainty_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uncertainty Analysis Record',
                'ordering': ['-created_at'],
            },
        ),
    ]
